export const GET_PLACES = 'GET_PLACES'
export const GET_PLACES_BY_ID = 'GET_PLACES_BY_ID'
export const ADD_PLACE= 'ADD_PLACE'
export const DELETE_PLACE = 'DELETE_PLACE'
export const UPDATE_PLACE = 'UPDATE_PLACE'
